---
AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket for SageMaker Studio
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: mllab
Resources:
  SageMakerS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${ProjectName}-sagemaker-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: IntelligentTiering
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
            # ExpirationInDays: 14
            NoncurrentVersionExpiration:
              NoncurrentDays: 7
Outputs:
  SageMakerS3Bucket:
    Description: S3 bucket for SageMaker
    Value: !Ref SageMakerS3Bucket
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-SageMakerS3Bucket
