---
AWSTemplateFormatVersion: 2010-09-09
Description: SageMaker Studio domain
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: mllab
  VpcStackName:
    Description: Set the VPC stack name.
    Type: String
    Default: vpc-private-subnets-and-endpoint-for-s3
  IamStackName:
    Description: Set the IAM stack name.
    Type: String
    Default: iam-roles-for-sagemaker
Resources:
  StudioDomain:
    Type: AWS::SageMaker::Domain
    Properties:
      DomainName: !Sub ${ProjectName}-sagemaker-studio-domain
      DefaultUserSettings:
        ExecutionRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-SageMakerExecutionRole
      VpcId:
        Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-VPC
      SubnetIds:
        - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
        - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
        - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
      AppNetworkAccessType: PublicInternetOnly
      AuthMode: IAM
  DefaultUserProfile:
    Type: AWS::SageMaker::UserProfile
    Properties:
      UserProfileName: !Sub ${ProjectName}-default-user-profile
      DomainId: !GetAtt StudioDomain.DomainId
      UserSettings:
        ExecutionRole:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-SageMakerExecutionRole
